# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='note',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
